"""empty message

Revision ID: 15c38aba9dde
Revises: 5bca226dd716
Create Date: 2023-06-27 15:22:36.275595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c38aba9dde'
down_revision = '5bca226dd716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
