"""empty message

Revision ID: 5bca226dd716
Revises: 900c8d2d5f42
Create Date: 2023-06-27 09:15:35.609952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bca226dd716'
down_revision = '900c8d2d5f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('managed_trail_systems', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('managed_trail_systems')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
