"""empty message

Revision ID: 900c8d2d5f42
Revises: a2ff8db95c27
Create Date: 2023-06-26 21:06:44.858996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '900c8d2d5f42'
down_revision = 'a2ff8db95c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_systems', schema=None) as batch_op:
        batch_op.alter_column('map',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_systems', schema=None) as batch_op:
        batch_op.alter_column('map',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
