"""Modified Equipment Model

Revision ID: a2ff8db95c27
Revises: b6578650ccb1
Create Date: 2023-06-26 15:34:39.548076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ff8db95c27'
down_revision = 'b6578650ccb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
